/* Shared, read-only mock catalog. User-created spots live in localStorage. */
const MOCK_SPOTS = [
  { id: "hbll-1-quiet", name: "Quiet Reading Room", building: "Harold B. Lee Library", floor: "1", position: { x: 22, y: 28 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: false, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "solo", busyness: "Usually busy", description: "A softly lit room with long tables, generous outlets, and a calm, focused feel." },
  { id: "hbll-2-north", name: "North Window Bar", building: "Harold B. Lee Library", floor: "2", position: { x: 68, y: 25 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "solo", busyness: "Moderate", description: "Bright individual stations beside the north windows, perfect for a reading sprint." },
  { id: "hbll-3-collab", name: "Third Floor Collaboration Zone", building: "Harold B. Lee Library", floor: "3", position: { x: 49, y: 58 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Usually busy", description: "Moveable tables and whiteboards for group work without leaving the library." },
  { id: "hbll-4-carrels", name: "Tower Carrels", building: "Harold B. Lee Library", floor: "4", position: { x: 78, y: 70 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: false, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "solo", busyness: "Usually empty", description: "High-up study carrels with mountain views and minimal foot traffic." },
  { id: "wsc-1-canyon", name: "Canyon Commons Booths", building: "Wilkinson Student Center", floor: "1", position: { x: 30, y: 65 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Usually busy", description: "Comfy booths near food options, useful for a quick study session between classes." },
  { id: "wsc-2-sunroom", name: "Sunroom Tables", building: "Wilkinson Student Center", floor: "2", position: { x: 65, y: 32 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "big group", busyness: "Moderate", description: "A social, sunny level with large tables that can handle bigger groups." },
  { id: "wsc-3-lounge", name: "Cougar Lounge", building: "Wilkinson Student Center", floor: "3", position: { x: 48, y: 44 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: false, wifi: true, tables: false, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Usually busy", description: "Soft seating and easy conversation for low-key collaborative work." },
  { id: "wsc-4-terrace", name: "Fourth Floor Terrace", building: "Wilkinson Student Center", floor: "4", position: { x: 75, y: 76 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: true }, groupSize: "small group", busyness: "Usually empty", description: "An outdoor terrace with tables and fresh air when you need a reset." },
  { id: "talmage-1-atrium", name: "Talmage Atrium", building: "Talmage Building", floor: "1", position: { x: 50, y: 38 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Moderate", description: "A central atrium with plenty of natural light and flexible seating." },
  { id: "talmage-2-nook", name: "East Stair Nook", building: "Talmage Building", floor: "2", position: { x: 24, y: 73 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: false, outlets: true, wifi: true, tables: false, comfySeating: true, outdoors: false }, groupSize: "solo", busyness: "Usually empty", description: "A tucked-away lounge chair near the east stairs for focused review." },
  { id: "talmage-3-seminar", name: "Seminar Hall Overflow", building: "Talmage Building", floor: "3", position: { x: 69, y: 42 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "big group", busyness: "Usually empty", description: "Open tables outside the seminar rooms, especially calm outside class changes." },
  { id: "law-1-reading", name: "Law Reading Room", building: "J. Reuben Clark Law School", floor: "1", position: { x: 28, y: 32 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: false, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "solo", busyness: "Moderate", description: "Classic library tables and armchairs with a quiet, academic atmosphere." },
  { id: "law-2-lounge", name: "Student Commons Lounge", building: "J. Reuben Clark Law School", floor: "2", position: { x: 74, y: 56 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Usually empty", description: "A comfortable commons with conversation-friendly tables and charging." },
  { id: "law-3-view", name: "Third Floor View Nook", building: "J. Reuben Clark Law School", floor: "3", position: { x: 54, y: 24 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: false, outlets: true, wifi: true, tables: false, comfySeating: true, outdoors: false }, groupSize: "solo", busyness: "Usually empty", description: "A small nook with a view toward campus and a handful of soft chairs." },
  { id: "eb-2-maker", name: "Maker Space Tables", building: "Engineering Building", floor: "2", position: { x: 35, y: 61 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "big group", busyness: "Moderate", description: "Large worktables with power for project teams and problem-solving sessions." },
  { id: "eb-3-glass", name: "Glass Hallway Bar", building: "Engineering Building", floor: "3", position: { x: 66, y: 27 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: false, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "small group", busyness: "Usually empty", description: "Long counter seating overlooking the quad, with quick access to outlets." },
  { id: "eb-4-senior", name: "Senior Project Loft", building: "Engineering Building", floor: "4", position: { x: 51, y: 70 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "big group", busyness: "Usually busy", description: "A lively upper-floor loft where project groups can spread out." },
  { id: "lsb-1-garden", name: "Life Sciences Garden", building: "Life Sciences Building", floor: "1", position: { x: 72, y: 66 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: false, wifi: true, tables: true, comfySeating: true, outdoors: true }, groupSize: "small group", busyness: "Usually empty", description: "Outdoor tables beside the teaching garden, with a relaxed atmosphere." },
  { id: "lsb-2-study", name: "Biology Study Bay", building: "Life Sciences Building", floor: "2", position: { x: 30, y: 34 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: false, outlets: true, wifi: true, tables: true, comfySeating: false, outdoors: false }, groupSize: "solo", busyness: "Moderate", description: "A focused row of tables near the labs with dependable campus WiFi." },
  { id: "lsb-3-atrium", name: "Atrium Soft Seats", building: "Life Sciences Building", floor: "3", position: { x: 60, y: 52 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: false, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Usually empty", description: "Soft seats overlooking the atrium for reading or informal discussion." },
  { id: "hinckley-1-patio", name: "Hinckley Patio", building: "Hinckley Center", floor: "1", position: { x: 40, y: 74 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: true }, groupSize: "big group", busyness: "Moderate", description: "A covered patio with big tables and a welcoming, social feel." },
  { id: "hinckley-2-salon", name: "International Salon", building: "Hinckley Center", floor: "2", position: { x: 62, y: 31 }, features: { quietZone: false, talkingAllowed: true, foodAllowed: true, outlets: true, wifi: true, tables: true, comfySeating: true, outdoors: false }, groupSize: "small group", busyness: "Usually empty", description: "An inviting lounge with soft chairs, tables, and plenty of natural light." },
  { id: "hinckley-3-window", name: "Third Floor Window Seats", building: "Hinckley Center", floor: "3", position: { x: 26, y: 26 }, features: { quietZone: true, talkingAllowed: false, foodAllowed: true, outlets: true, wifi: true, tables: false, comfySeating: true, outdoors: false }, groupSize: "solo", busyness: "Usually empty", description: "Quiet window seats for solo work, with a little ambient hallway energy." }
];

const BUILDINGS = [
  { name: "Engineering Building", short: "Engineering", x: 25, y: 22, w: 170, h: 96, color: "mint" },
  { name: "Harold B. Lee Library", short: "HBLL", x: 350, y: 18, w: 210, h: 126, color: "sky" },
  { name: "Wilkinson Student Center", short: "WSC", x: 690, y: 38, w: 208, h: 112, color: "peach" },
  { name: "Talmage Building", short: "Talmage", x: 92, y: 264, w: 188, h: 112, color: "lavender" },
  { name: "J. Reuben Clark Law School", short: "Law School", x: 394, y: 260, w: 240, h: 120, color: "yellow" },
  { name: "Life Sciences Building", short: "Life Sciences", x: 744, y: 250, w: 188, h: 116, color: "coral" },
  { name: "Hinckley Center", short: "Hinckley", x: 688, y: 452, w: 210, h: 112, color: "blue" }
];

const FEATURE_META = [
  ["quietZone", "Quiet zone", "Quiet"],
  ["talkingAllowed", "Talking allowed", "Talk"],
  ["foodAllowed", "Food allowed", "Food"],
  ["outlets", "Outlets", "Power"],
  ["wifi", "WiFi", "WiFi"],
  ["tables", "Tables", "Tables"],
  ["comfySeating", "Comfy seating", "Comfy"],
  ["outdoors", "Outdoors", "Outside"]
];

const GROUP_SIZES = ["solo", "small group", "big group"];
const BUSYNESS_ORDER = { "Usually empty": 0, "Moderate": 1, "Usually busy": 2 };
